### ISSUE TITLE
Forward grammar to the first object

### ISSUE THREAD

**Issue by maziarkanani** [grantjenks/scikit-sequitur#11]
I want to have the string that comes from a grammar. In fact, by having a grammar that we don't know what belongs to, reach the elements of the string (in the forward process of what the sequitur algorithm does). Now I wonder if there is any function for that in the scikit-sequitur package. If not, could you please tell me how can I have access the right part of the grammar parse export? As an example, in the following photo in the second line we have Production(5) which we have access to     7 c         but I want to have access to       gcc

![Untitleddd](https://user-images.githubusercontent.com/47989173/205993432-ba4aa430-02f9-4069-a748-ea2af0ece70b.jpg)

I didn't find any related code to the right export part in what you put here.

**Comment by grantjenks** [comment]
I think you want `grammar.expand` like so:

```python
In [8]: from sksequitur import parse

In [9]: grammar = parse('jffdjfdfsfkjfdljfjfsfdsfejlffdsf')

In [10]: print(grammar)
0 -> 1 2 3 f 4 k 3 l 1 1 4 d 4 e j l f 2 4
1 -> j f                                          jf
2 -> f d                                          fd
3 -> 1 d                                          jfd
4 -> s f                                          sf

In [11]: grammar[3]
Out[11]: [Production(1), 'd']

In [12]: list(grammar.expand(3))
Out[12]: ['j', 'f', 'd']
```

**Comment by maziarkanani** [comment]
perfect. Thank you very much
